export const materias = [
  { label: "ABP", value: "abp" },
  { label: "Ambiental/Rural", value: "ambiental_rural" },
  { label: "Chefia e Liderança", value: "chefia_lideranca" },
  { label: "COMOP", value: "comop" },
  { label: "Defesa Pessoal", value: "defesa_pessoal" },
  { label: "Direitos Humanos", value: "direitos_humanos" },
  { label: "Fip", value: "fip" },
  { label: "FPC", value: "fpc" },
  { label: "FPT", value: "fpt" },
  { label: "Fundamentos Institucionais", value: "fundamentos_institucionais" },
  { label: "História da PMDF", value: "historia_da_pmdf" },
  { label: "IPMOVD", value: "ipmovd" },
  { label: "LegIn", value: "legin" },
  { label: "Libras", value: "libras" },
  { label: "Ordem Unida", value: "ordem_unida" },
  { label: "PAD", value: "pad" },
  { label: "PP", value: "pp" },
  { label: "Redação oficial", value: "redacao_oficial" },
  { label: "ReInter", value: "reinter" },
  { label: "TCO", value: "tco" },
  { label: "TJAP", value: "tjap" },
  { label: "TTML", value: "ttml" },
  { label: "TTP", value: "ttp" },
  { label: "VCCS", value: "vccs" },

];

